pip install --upgrade aioredis
pip install --upgrade alembic
pip install --upgrade altgraph
pip install --upgrade aniso8601
pip install --upgrade appdirs
pip install --upgrade asn1crypto
pip install --upgrade aspy.yaml
pip install --upgrade astroid
pip install --upgrade async-timeout
pip install --upgrade atomicwrites
pip install --upgrade attrs
pip install --upgrade Babel
pip install --upgrade beautifulsoup4
pip install --upgrade black
pip install --upgrade blinker
pip install --upgrade bs4
pip install --upgrade cached-property
pip install --upgrade certifi
pip install --upgrade cffi
pip install --upgrade cfgv
pip install --upgrade chardet
pip install --upgrade Click
pip install --upgrade colorama
pip install --upgrade coverage
pip install --upgrade cryptography
pip install --upgrade cycler
pip install --upgrade dash
pip install --upgrade dash-core-components
pip install --upgrade dash-html-components
pip install --upgrade dash-renderer
pip install --upgrade dash-table
pip install --upgrade defusedxml
pip install --upgrade Django
pip install --upgrade dominate
pip install --upgrade easyimap
pip install --upgrade emoji
pip install --upgrade emoji-country-flag
pip install --upgrade entrypoints
pip install --upgrade et-xmlfile
pip install --upgrade Faker
pip install --upgrade flake8
pip install --upgrade Flask
pip install --upgrade Flask-Babel
pip install --upgrade Flask-Bootstrap
pip install --upgrade Flask-Compress
pip install --upgrade Flask-Excel
pip install --upgrade Flask-Login
pip install --upgrade Flask-Mail
pip install --upgrade Flask-Migrate
pip install --upgrade Flask-Moment
pip install --upgrade Flask-RESTful
pip install --upgrade Flask-SocketIO
pip install --upgrade Flask-SQLAlchemy
pip install --upgrade Flask-Table
pip install --upgrade Flask-Uploads
pip install --upgrade Flask-WTF
pip install --upgrade future
pip install --upgrade guess-language-spirit
pip install --upgrade gunicorn
pip install --upgrade hiredis
pip install --upgrade identify
pip install --upgrade idna
pip install --upgrade image
pip install --upgrade IMAPClient
pip install --upgrade importlib-metadata
pip install --upgrade importlib-resources
pip install --upgrade isodate
pip install --upgrade isort
pip install --upgrade itsdangerous
pip install --upgrade jdcal
pip install --upgrade Jinja2
pip install --upgrade json2html
pip install --upgrade kiwisolver
pip install --upgrade lazy-object-proxy
pip install --upgrade lml
pip install --upgrade lxml
pip install --upgrade Mako
pip install --upgrade MarkupSafe
pip install --upgrade matplotlib
pip install --upgrade mccabe
pip install --upgrade more-itertools
pip install --upgrade ndg-httpsclient
pip install --upgrade nodeenv
pip install --upgrade numpy
pip install --upgrade openpyxl
pip install --upgrade packaging
pip install --upgrade pandas
pip install --upgrade pandas-datareader
pip install --upgrade pdfminer3k
pip install --upgrade pefile
pip install --upgrade Pillow
pip install --upgrade plotly
pip install --upgrade pluggy
pip install --upgrade ply
pip install --upgrade pre-commit
pip install --upgrade psutil
pip install --upgrade psycopg2
pip install --upgrade py
pip install --upgrade pyasn1
pip install --upgrade pyassert
pip install --upgrade PyAutoGUI
pip install --upgrade pycodestyle
pip install --upgrade pycparser
pip install --upgrade pycurl
pip install --upgrade pyexcel
pip install --upgrade pyexcel-io
pip install --upgrade pyexcel-webio
pip install --upgrade pyfix
pip install --upgrade pyflakes
pip install --upgrade PyInstaller
pip install --upgrade PyJWT
pip install --upgrade pylint
pip install --upgrade PyMsgBox
pip install --upgrade PyMySQL
pip install --upgrade pyOpenSSL
pip install --upgrade pyparsing
pip install --upgrade PyScreeze
pip install --upgrade pytest
pip install --upgrade pytest-asyncio
pip install --upgrade pytest-env
pip install --upgrade pytest-socket
pip install --upgrade pytest-sugar
pip install --upgrade python-dateutil
pip install --upgrade python-dotenv
pip install --upgrade python-editor
pip install --upgrade python-engineio
pip install --upgrade python-socketio
pip install --upgrade python-telegram-bot
pip install --upgrade PyTweening
pip install --upgrade pytz
pip install --upgrade pyupgrade
pip install --upgrade pywin32-ctypes
pip install --upgrade PyYAML
pip install --upgrade pyzmail36
pip install --upgrade requests
pip install --upgrade requests-toolbelt
pip install --upgrade retrying
pip install --upgrade selenium
pip install --upgrade simplefix
pip install --upgrade six
pip install --upgrade slowbreak
pip install --upgrade SQLAlchemy
pip install --upgrade suds-jurko
pip install --upgrade text-unidecode
pip install --upgrade texttable
pip install --upgrade tokenize-rt
pip install --upgrade toml
pip install --upgrade tornado
pip install --upgrade typed-ast
pip install --upgrade unsync
pip install --upgrade urllib3
pip install --upgrade virtualenv
pip install --upgrade visitor
pip install --upgrade wcwidth
pip install --upgrade Werkzeug
pip install --upgrade wrapt
pip install --upgrade WTForms
pip install --upgrade xlrd
pip install --upgrade zeep
pip install --upgrade zipp
